### PR TITLE
Create genderpred

### PR DESCRIPTION
**Pull request by carmenbr61**
Predicting chromosomal gender from expression data based on Kmeans algorithm

### CODE REVIEW

**Comment by PeteHaitch** [comment]
I think this should be called sex prediction rather than gender prediction. See http://www.med.monash.edu.au/gendermed/sexandgender.html for a brief explanation why this is important

**Comment by lwaldron** [comment]
Yes, Peter is correct.

**Comment by LiNk-NY** [comment]
Thanks @PeteHaitch. I will create an issue for it.

**Comment by ttriche** [comment]
could use the minfi::getSex() function as a prototype, even though it fits
on chrX & chrY copy number (since a male losing chrX is not uncommon, but a
female gaining chrY is).  Point here is that having a two-pass strategy
seems to help with unexpected losses or gains.  I found that a binomial
test for X-inactivation based on DNA methylation was another failsafe.  If
all of them suggest that only one sex of subjects is present, that's
usually correct :-)

I'm not sure how many gender-discriminative autosomal genes there are that
stay that way across tissues, but perhaps clustering on a healthy dose of
them will solve that problem. There's a cheezy old trick from the CAFE
package that might help, as well -- take the mean expression of all
transcripts that escape X inactivation and use those to estimate chrX copy
number.  Do the same for chrY.  See if that agrees with the autosomal sex
prediction.





--t

**Comment by lima1** [comment]
I have two additional functions in the PureCn package in case this is relevant here. First one looks at X vs Y coverage ratio.  If the commonly used sex marker genes such as AMELY or SRY are covered, it is usually black and white and very accurate. Loss of Y is not too rare, so you also want to check for heterozygous SNPs on X. Contamination and artifacts are also common, so you need to set parameters not too stringently. Min Allelic fraction of 0.2 seems to work fine in a Fisher test. The advantage of these functions is that they work for single samples. So in contrast to cluster methods, they would also work fine for small or single sex datasets.

**Comment by lwaldron** [comment]
Thanks Tim and Markus. Carmen, would you check these functions out also?

**Comment by LiNk-NY** [comment]
I'm tagging her here @carmenbr61

**Pull request merged**
